[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/invitation-request"
  to = "/invitation-request.html"
  status = 200

[[redirects]]
  from = "/invitation-thanks"
  to = "/invitation-thanks.html"
  status = 200
